// <auto-generated />
namespace BusinessCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserObject3autoGenId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserObject3autoGenId));
        
        string IMigrationMetadata.Id
        {
            get { return "201709162104302_UserObject-3-autoGenId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
